---
abstract: 'Really return() from a try/catch-block'
author:
  - 'Marcel Gruenauer <marcel@cpan.org>'
build_requires:
  Carp: 0
  English: 0
  File::Find: 0
  File::Temp: 0
  Scalar::Util: 0
  Test::More: 0.94
  Try::Tiny: 0
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200004, CPAN::Meta::Converter version 2.110440'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Error-Return
provides:
  Error::Return:
    file: lib/Error/Return.pm
    version: 1.110510
requires:
  Exporter: 0
  Scope::Upper: 0
  perl: 5.008
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Error-Return
  homepage: http://search.cpan.org/dist/Error-Return/
  repository: git://github.com/hanekomu/Error-Return.git
version: 1.110510
