---
abstract: 'return(), skipping a scope'
author:
  - 'Marcel Gruenauer <marcel@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.11
generated_by: 'Dist::Zilla version 1.100711'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Error-Return
provides:
  Error::Return:
    file: lib/Error/Return.pm
    version: 1.100850
requires:
  Carp: 0
  English: 0
  Error: 0
  Exporter: 0
  File::Find: 0
  File::Temp: 0
  Scalar::Util: 0
  Scope::Upper: 0
  Test::More: 0.88
  perl: 5.008
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Error-Return
  homepage: http://search.cpan.org/dist/Error-Return/
  repository: http://github.com/hanekomu/Error-Return
version: 1.100850
